In [1]:
import numpy as np
array = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

In [2]:
print(array)

[[1 3 5]
 [2 4 6]]


In [3]:
array.ndim

2

In [4]:
array.shape

(2, 3)

In [5]:
array.size

6

In [7]:
a = np.array([2, 23, 4], dtype=np.int32)
a

array([ 2, 23,  4], dtype=int32)

In [8]:
a.dtype

dtype('int32')

In [10]:
np.array([[2, 3, 4],
         [3, 4, 5]])

array([[2, 3, 4],
       [3, 4, 5]])

In [11]:
np.zeros((3, 4,))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
a = np.empty((3, 4), dtype=int)
print(a)

[[    139651996507472            36164368                   0
                    0]
 [                  0 8319683848551211643 3180222411935070754
  8391722768137527840]
 [7959390389040738153 2318290791345824372 8675445202132104482
  7957695011165139568]]


In [25]:
a = np.arange(10, 21, 2)
print(a)

[10 12 14 16 18 20]


In [26]:
b = a.reshape((2, 3))
print(b)

[[10 12 14]
 [16 18 20]]


In [27]:
a = np.linspace(1, 10, 20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [28]:
b = a.reshape((5, 4))
print(b)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


In [29]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, b)

[10 20 30 40] [0 1 2 3]


In [31]:
c = a - b
print(c)

[10 19 28 37]


In [32]:
print(a*b)

[  0  20  60 120]


In [33]:
print(a**2)

[ 100  400  900 1600]


In [34]:
print(np.sin(a))

[-0.54402111  0.91294525 -0.98803162  0.74511316]


In [35]:
print(b < 2)

[ True  True False False]


In [36]:
d = np.array([1, 1, 4, 3])

In [38]:
print(b == d)

[False  True False  True]


In [41]:
a = np.array([[1, 1],[0, 1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [42]:
print(a.dot(b))

[[2 4]
 [2 3]]


In [43]:
print(np.dot(a, b))

[[2 4]
 [2 3]]


In [44]:
a = np.random.random((2,4))
print(a)
print(np.sum(a))

[[0.55232177 0.46523977 0.44229713 0.11999102]
 [0.89138937 0.1078687  0.40403201 0.74946645]]
3.7326062212098745


In [45]:
print(np.min(a))

0.10786869813478506


In [46]:
print(np.max(a))

0.8913893723258566


In [47]:
np.sum(a, axis=1)

array([1.57984969, 2.15275653])

In [48]:
np.sum(a, axis=0)

array([1.44371114, 0.57310846, 0.84632915, 0.86945747])

In [49]:
np.min(a, axis=1)

array([0.11999102, 0.1078687 ])

In [50]:
np.max(a, axis=0)

array([0.89138937, 0.46523977, 0.44229713, 0.74946645])

In [51]:
A = np.arange(2, 14).reshape((3, 4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [57]:
np.argmin(A)

0

In [58]:
np.argmax(A)

11

In [59]:
np.mean(A)

7.5

In [60]:
np.average(A)

7.5

In [61]:
A.mean()

7.5

In [62]:
np.median(A)

7.5

In [63]:
np.cumsum(A)

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [64]:
np.diff(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [65]:
A = np.arange(14, 2, -1).reshape((3, 4))
print(A)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [67]:
np.sort(A)

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

In [68]:
np.transpose(A)

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [69]:
A.T

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [70]:
A

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

In [71]:
np.clip(A, 5, 9)

array([[9, 9, 9, 9],
       [9, 9, 8, 7],
       [6, 5, 5, 5]])

In [72]:
np.clip(A, 4, 10)

array([[10, 10, 10, 10],
       [10,  9,  8,  7],
       [ 6,  5,  4,  4]])

In [1]:
import numpy as np

In [3]:
A = np.arange(3, 15)
A

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
print(A[3])

6


In [6]:
B = A.reshape(3, 4)
B

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [7]:
B[2]

array([11, 12, 13, 14])

In [8]:
B[0][2]

5

In [9]:
B[0, 2]

5

In [10]:
B[1, 1:3]

array([8, 9])

In [11]:
for row in B:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [12]:
for column in B.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [13]:
A.flatten()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [15]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

In [16]:
A

array([1, 1, 1])

In [17]:
B

array([2, 2, 2])

In [19]:
C = np.vstack((A, B))

In [20]:
C

array([[1, 1, 1],
       [2, 2, 2]])

In [21]:
A.shape, B.shape, C.shape

((3,), (3,), (2, 3))

In [22]:
D = np.hstack((A, B))
D

array([1, 1, 1, 2, 2, 2])

In [23]:
print(A.shape, B.shape, D.shape)

(3,) (3,) (6,)


In [24]:
A[np.newaxis, :]

array([[1, 1, 1]])

In [25]:
A[:, np.newaxis]

array([[1],
       [1],
       [1]])

In [26]:
A[:, np.newaxis].shape

(3, 1)

In [27]:
A = A[:, np.newaxis]
A

array([[1],
       [1],
       [1]])

In [28]:
B = B[:, np.newaxis]
B

array([[2],
       [2],
       [2]])

In [29]:
np.concatenate((A,B,B,A), axis=0)

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1]])

In [30]:
np.concatenate((A,B,B,A), axis=1)

array([[1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 2, 2, 1]])

In [32]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
b = np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
c = np.concatenate((a,b), axis=0)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
c = np.concatenate((a,b), axis=1)
c

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [37]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
np.split(A, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [40]:
np.split(A, 3, axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [42]:
np.split(A, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [43]:
np.array_split(A, 3, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [44]:
np.vsplit(A, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [45]:
np.hsplit(A, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [46]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [47]:
b = a
c = a
d = a

In [48]:
b is a

True

In [49]:
a[0] = 11

In [50]:
a

array([11,  1,  2,  3])

In [51]:
b

array([11,  1,  2,  3])

In [52]:
c

array([11,  1,  2,  3])

In [53]:
d

array([11,  1,  2,  3])

In [54]:
d[1:3] = [22, 33]

In [55]:
a

array([11, 22, 33,  3])

In [56]:
c

array([11, 22, 33,  3])

In [57]:
b

array([11, 22, 33,  3])

In [58]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [59]:
b = a.copy()

In [60]:
b

array([0, 1, 2, 3])

In [61]:
a[3] = 44

In [62]:
b

array([0, 1, 2, 3])

In [64]:
from numpy import array

In [66]:
a = array([[0, 0, 0,],
           [10, 10, 10],
           [20, 20, 20],
           [30, 30, 30]])
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [67]:
b = array([0, 1, 2])
b

array([0, 1, 2])

In [68]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])